MT-07 CAN Bus Documentation: main.ino File Reference
main.ino File Reference
Main program for MT-07 CAN Bus Interface.
#include "MT07_CANBus.h"
Functions
MT07_CANBus mt07 (CS_PIN)
Instance of the MT07_CANBus class.
void setup ()
Arduino setup function.
void loop ()
Arduino loop function.
Variables
const int CS_PIN = 5
Chip select pin for MCP2515.
Detailed Description
Main program for MT-07 CAN Bus Interface.
This program uses the MT07_CANBus library to interact with the CAN bus of a Yamaha MT-07 motorcycle (2014 model). It initializes the CAN bus, decodes incoming messages, and displays the following data in real-time:
Gear position
Throttle position sensor (TPS)
Motor and air temperature
Speed and RPM
Author
Andreas Panagiotakis
Date
2024-08-03 \license MIT License
\usage
Connect the MCP2515 module to the ESP32.
Wire the CAN bus to the motorcycle.
Compile and upload the program to the ESP32.
View the decoded data in the Serial Monitor at 115200 baud.
Definition in file main.ino.
Function Documentation
loop()
void loop ()
Arduino loop function.
Checks for incoming CAN messages, processes them, and displays the decoded data in the Serial Monitor.
Definition at line 52 of file main.ino.
            {
    unsigned long rxId;
    byte rxBuf[8];
    byte rxDlc;
    // Check for incoming CAN messages
    if (CAN_MSGAVAIL == mt07.CAN.checkReceive()) {
        if (mt07.CAN.readMsgBuf(&rxId, &rxDlc, rxBuf) == CAN_OK) {
            mt07.processMessage(rxId, rxBuf);  // Decode the message
            // Display decoded data
            Serial.print("Gear Position: ");
            Serial.println(mt07.getGearPosition());
            Serial.print("TPS: ");
            Serial.print(mt07.getTPS());
            Serial.println("%");
            Serial.print("Motor Temp: ");
            Serial.println(mt07.getMotorTemp());
            Serial.print("Air Temp: ");
            Serial.println(mt07.getAirTemp());
            Serial.print("Speed: ");
            Serial.print(mt07.getSpeed());
            Serial.println(" km/h");
            Serial.print("RPM: ");
            Serial.println(mt07.getRPM());
            Serial.println("---------------------------");
        } else {
            Serial.println("Error reading CAN message.");
        }
    }
}
References mt07().
mt07()
MT07_CANBus mt07 (CS_PIN)
Instance of the MT07_CANBus class.
References CS_PIN.
Referenced by loop(), and setup().
setup()
void setup ()
Arduino setup function.
Initializes the Serial Monitor and CAN bus. If the CAN bus fails to initialize, the program halts.
Definition at line 36 of file main.ino.
             {
    Serial.begin(115200);
    if (mt07.begin(CAN_500KBPS, MCP_8MHZ)) {
        Serial.println("MT-07 CANBus initialized successfully.");
    } else {
        Serial.println("Failed to initialize MT-07 CANBus.");
        while (1);  // Halt the program if initialization fails
    }
}
References mt07().
Variable Documentation
CS_PIN
const int CS_PIN = 5
Chip select pin for MCP2515.
Definition at line 26 of file main.ino.
Referenced by mt07().